### ISSUE TITLE
Authentication doesn't works..

### ISSUE THREAD

**Issue by FlavioFabbrizi** [mdhom/node-red-contrib-google-oauth-calendar#2]
I've created my credentials and imported from json file.
When I click "open google authentication" it doesnt works.
using inspector I see this url (192.168.178:8123 is my home assistant base url):
192.168.178.50:8123/google-credentials/authUrl/123456789000/12345666xxxxxxxxxxxxxxx.apps.googleusercontent.com/urn:ietf:wg:oauth:2.0:oob

do you think I can you use it with home assistant and node-red or I must do same special configuration? (eg. hostname)
thsnk

**Comment by Dirnei** [comment]
The best is to use node-red directly. Just go to 192.168.178.50:1880 in your case. It should work there

**Comment by mdhom** [comment]
@FlavioFabbrizi did you try Dirneis proposal? Please let me know if it worked that way!

**Comment by FlavioFabbrizi** [comment]
> @FlavioFabbrizi did you try Dirneis proposal? Please let me know if it worked that way!

It works fine! You solve all my issues with this module!

**Comment by jkmaxwell** [comment]
Hi, please reopen @mdhom  — I am having this problem running under Hassio and the workaround does not work because I get a 400 bad request when trying to access port 1880, even though that's what is in my configuration. Thank you in advance @Dirnei 

I'm able to access https://192.168.1.222:1880/endpoint/ui/ but not the editor at /

It appears this is an issue for everyone now
https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#known-issues-and-limitations

Perhaps you can tell us a workaround we can manually enter for the URL to authenticate, instead?
